version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        # The ECS service name to update
        TaskDefinition: "arn:aws:ecs:ap-southeast-1:767398055677:task-definition/task"
        #arn:aws:ecs:ap-southeast-1:767398055677:task-definition/task:9
        LoadBalancerInfo:
          ContainerName: "task"
          ContainerPort: 3000
# hooks:
#   BeforeInstall:
#     - location: scripts/before-install.sh
#       timeout: 300
#       runas: root
#   AfterInstall:
#     - location: scripts/docker-cleanup.sh
#       timeout: 180
#       runas: root
#   AfterAllowTestTraffic:
#     - location: scripts/health-check.sh
#       timeout: 300
#       runas: root
